name: rich_readmore
description: A widget that displays text with an option to show more or show less based on the provided settings.
version: 1.0.5
repository: https://github.com/thierryoliveira/rich_readmore

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

